name: Update Portfolio Data
on:
  schedule:
    # Run every 15 minutes (fixed cron syntax)
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Give the workflow write permissions to the repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true  # Ensure credentials are passed to later steps

      - name: Debug - Check repository structure
        run: |
          echo "Repository structure:"
          find . -type f -name "*.py" | head -10
          echo "Dashboard directory:"
          ls -la dashboard/ || echo "Dashboard directory not found"
          echo "Update jobs directory:"
          ls -la dashboard/update_jobs/ || echo "Update jobs directory not found"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            echo "Installing from requirements.txt"
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, installing common packages"
            pip install python-dotenv alpaca-py
          fi

      - name: Debug - Check environment
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_PAPER: ${{ secrets.ALPACA_PAPER }}
        run: |
          echo "Python version:"
          python --version
          echo "Current directory:"
          pwd
          echo "Environment check:"
          echo "ALPACA_API_KEY is set: $([ -n "$ALPACA_API_KEY" ] && echo 'Yes' || echo 'No')"
          echo "ALPACA_SECRET_KEY is set: $([ -n "$ALPACA_SECRET_KEY" ] && echo 'Yes' || echo 'No')"
          echo "ALPACA_PAPER: ${ALPACA_PAPER:-'not set'}"

      - name: Run update job
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_PAPER: ${{ secrets.ALPACA_PAPER }}
        run: |
          echo "=== Starting update job ==="
          echo "Current directory: $(pwd)"
          echo "Changing to dashboard/update_jobs"
          cd dashboard/update_jobs
          echo "New directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Running positions_job.py..."
          python positions_job.py
          echo "=== Update job completed ==="

      - name: Check for new files
        run: |
          echo "Checking data directory:"
          ls -la dashboard/data/snapshots/ | tail -10 || echo "Snapshots directory not found"
          echo "Git status:"
          git status dashboard/data/snapshots/ || echo "No snapshots directory in git"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          echo "Checking for changes..."
          git status --porcelain dashboard/data/snapshots/
          
          if [[ -n $(git status --porcelain dashboard/data/snapshots/) ]]; then
            echo "✅ Changes detected, committing..."
            git add dashboard/data/snapshots/
            git commit -m "Update portfolio data [skip ci]"
            git push
            echo "✅ Changes pushed successfully."
          else
            echo "ℹ️  No changes to commit."
          fi